# Generated by Django 5.1.3 on 2024-11-07 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=100000)),
                ('data', models.DateField()),
                ('repeticao', models.CharField(choices=[('Unica', 'Única'), ('Parcelada', 'Parcelada'), ('Fixa', 'Fixa')], default='Unica', max_length=10)),
                ('categoria', models.CharField(choices=[('Automovel', 'Automóvel'), ('Bem_Estar', 'Bem Estar'), ('Educacao', 'Educação'), ('Funcionarios', 'Funcionários'), ('Lazer', 'Lazer'), ('Moradia', 'Moradia'), ('Saude', 'Saúde'), ('Seguros', 'Seguros'), ('Transporte', 'Transporte'), ('Vestuario', 'Vestuário'), ('Celular', 'Celular'), ('Investimentos', 'Investimentos'), ('Outras_Despesas', 'Outras Despesas')], max_length=30)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
