celebridades = [
    "Neymar Jr.",
    "Anitta",
    "Ivete Sangalo",
    "Caetano Veloso",
    "Gilberto Gil",
    "Sandy",
    "Luciano Huck",
    "Angélica",
    "Rodrigo Faro",
    "Gisele Bündchen",
    "Bruna Marquezine",
    "Marina Ruy Barbosa",
    "Paulo Gustavo",
    "Tatá Werneck",
    "Larissa Manoela",
    "Whindersson Nunes",
    "Felipe Neto",
    "Faustão",
    "Xuxa Meneghel",
    "Ana Maria Braga",
    "Fábio Porchat",
    "Lázaro Ramos",
    "Taís Araújo",
    "Fernanda Montenegro",
    "Grazi Massafera",
    "Tony Ramos",
    "Reynaldo Gianecchini",
    "Deborah Secco",
    "Rodrigo Santoro",
    "Ayrton Senna",
    "Pelé",
    "Ronaldo Fenômeno",
    "Zeca Pagodinho",
    "Daniel Alves",
    "Thiaguinho",
    "Marília Mendonça",
    "Luan Santana",
    "Gusttavo Lima",
    "Jorge e Mateus",
    "Alok",
    "Lionel Messi",
    "Cristiano Ronaldo",
    "Beyoncé",
    "Rihanna",
    "Shakira",
    "Michael Jackson",
    "Angelina Jolie",
    "Brad Pitt",
    "Leonardo DiCaprio",
    "Tom Cruise",
    "Dwayne Johnson (The Rock)",
    "Will Smith",
    "Robert Downey Jr.",
    "Johnny Depp",
    "Chris Hemsworth",
    "Scarlett Johansson",
    "Lady Gaga",
    "Adele",
    "Justin Bieber",
    "Selena Gomez",
    "Kanye West",
    "Kim Kardashian",
    "Elon Musk",
    "Jeff Bezos",
    "Mark Zuckerberg",
    "Jennifer Lopez",
    "Taylor Swift",
    "Eminem",
    "Snoop Dogg",
    "David Beckham",
    "Serena Williams",
    "LeBron James",
    "Silvio Santos"
]

perguntasCelebridades = [
    "Essa celebridade é brasileira?",
    "Essa pessoa é mais conhecida por atuar em filmes?",
    "Essa celebridade é um(a) cantor(a)?",
    "Ela já participou de uma novela brasileira?",
    "Essa pessoa é um(a) influenciador(a) digital?",
    "Ele(a) já ganhou um Oscar?",
    "Essa celebridade é conhecida internacionalmente?",
    "Ele(a) faz parte de uma banda ou grupo musical?",
    "Essa pessoa já foi casada com alguém famoso?",
    "Essa celebridade é conhecida por seu trabalho na TV?",
    "Essa pessoa já foi ao programa do Faustão?",
    "Ele(a) já fez sucesso em reality shows?",
    "Essa celebridade já foi polêmica nas redes sociais?",
    "Ele(a) é famoso por ser jogador(a) de futebol?",
    "Essa pessoa tem mais de 40 anos?",
    "Ele(a) é famoso(a) entre o público jovem?",
    "Essa celebridade já ganhou um Grammy?",
    "Ele(a) já trabalhou em Hollywood?",
    "Essa pessoa já esteve em turnê mundial?",
    "Essa celebridade já lançou algum livro?",
    "Ele(a) é mais conhecido(a) pela atuação em séries de TV?",
    "Essa pessoa tem uma fortuna bilionária?",
    "Ele(a) é um(a) ativista de causas sociais?",
    "Essa celebridade é casada com outra pessoa famosa?",
    "Ele(a) é conhecido(a) pelo seu estilo de moda?",
    "Essa pessoa já se envolveu em escândalos públicos?",
    "Ele(a) é conhecido(a) por ser apresentador(a) de TV?",
    "Essa celebridade tem filhos?",
    "Ele(a) foi muito famoso(a) nos anos 2000?",
    "Essa pessoa tem alguma relação com a política?",
    "Ele(a) já foi jurado(a) em programas de talento?",
    "Essa celebridade é famosa por comédias?",
    "Ele(a) já participou de campanhas publicitárias internacionais?",
    "Essa pessoa é conhecida por sua participação em redes sociais?",
    "Ele(a) já ganhou um prêmio no Brasil?",
    "Essa celebridade já gravou filmes de ação?",
    "Ele(a) já se envolveu em brigas públicas?",
    "Essa pessoa é mais famosa por sua carreira musical ou atuação?",
    "Ele(a) já apareceu em programas de entrevistas famosos?",
    "Essa celebridade é respeitada por seu trabalho humanitário?",
    "Ele(a) já estrelou uma franquia de filmes famosos?",
    "Essa pessoa já recebeu homenagens no Brasil?",
    "Ele(a) é famoso(a) por interpretar personagens icônicos?",
    "Essa celebridade já se aposentou?",
    "Ele(a) já recebeu prêmios importantes por suas performances?",
    "Essa pessoa já fez par romântico com outra celebridade famosa?",
    "Ele(a) já fez campanhas de conscientização?",
    "Essa celebridade é popular em premiações de cinema ou música?",
    "Ele(a) já fez uma participação em filmes de animação?",
    "Essa pessoa tem uma marca de roupas ou produtos?",
    "Ele(a) já foi destaque em capas de revistas internacionais?",
    "Essa celebridade é muito ativa no Instagram?",
    "Ele(a) já fez sucesso em mais de uma área (música, atuação, etc.)?",
    "Essa pessoa já recebeu algum título de 'Ícone do Ano'?",
    "Ele(a) já foi considerado(a) um sex symbol?",
    "Essa celebridade já se envolveu em causas ambientais?",
    "Ele(a) é conhecido(a) por suas declarações polêmicas?",
    "Essa pessoa já fez alguma aparição surpresa em eventos públicos?",
    "Ele(a) é uma das pessoas mais seguidas nas redes sociais?",
    "Essa celebridade já trabalhou com diretores renomados?",
    "Ele(a) já se apresentou em grandes estádios?",
    "Essa pessoa já foi notícia por sua vida pessoal?",
    "Ele(a) já participou de algum programa de talentos?",
    "Essa celebridade é conhecida por ser discreta sobre sua vida pessoal?",
    "Ele(a) já fez parceria com grandes marcas?",
    "Essa pessoa já atuou ou cantou em mais de um idioma?",
    "Ele(a) tem uma grande base de fãs no Brasil?",
    "Essa celebridade já fez uma participação especial em uma novela?",
    "Ele(a) é conhecido(a) por seu humor ou carisma?",
    "Essa pessoa já apresentou algum evento famoso?",
    "Ele(a) tem uma carreira consolidada há mais de 10 anos?",
    "Essa celebridade já participou de um clipe musical famoso?",
    "Ele(a) é uma referência no mundo da moda?",
    "Essa pessoa já foi considerada uma das pessoas mais influentes do mundo?",
    "Ele(a) já estrelou em propagandas de produtos de luxo?",
    "Essa celebridade já ganhou prêmios internacionais de prestígio?",
    "Ele(a) já interpretou um personagem histórico?",
    "Essa pessoa é conhecida por seus discursos inspiradores?",
    "Ele(a) tem um documentário ou filme biográfico?",
    "Essa celebridade já fez apresentações no Brasil?",
    "Ele(a) já foi notícia por adoções de causas humanitárias?",
    "Essa pessoa é conhecida por seu envolvimento em esportes?",
    "Ele(a) já recebeu prêmios em mais de uma área (música, cinema, TV)?",
    "Essa celebridade já participou de algum filme de super-heróis?",
    "Ele(a) é conhecido(a) por ter um estilo de vida extravagante?",
    "Essa pessoa já fez shows no Brasil?",
    "Ele(a) já fez declarações políticas públicas?",
    "Essa celebridade é reconhecida por sua beleza?",
    "Ele(a) já fez parte de um grupo musical famoso?",
    "Essa pessoa já lançou sua própria marca de beleza ou cosméticos?",
    "Ele(a) tem um grande número de seguidores no YouTube?",
    "Essa celebridade é conhecida por ter um estilo único e ousado?",
    "Ele(a) já ganhou algum tipo de título honorário?",
    "Essa pessoa já apareceu em comerciais de televisão no Brasil?",
    "Ele(a) já atuou em mais de um gênero de filmes?",
    "Essa celebridade tem uma carreira que já dura mais de 20 anos?",
    "Ele(a) já teve um programa próprio na televisão?",
    "Essa pessoa já foi reconhecida por sua filantropia?",
    "Essa celebridade é mais conhecida nos últimos 10 anos?",
    "Ele(a) já foi casado(a) com outra celebridade brasileira?",
    "Essa celebridade já participou de mais de 5 filmes?",
    "Ele(a) é conhecido(a) por fazer dublagens em filmes de animação?",
    "Essa pessoa é uma estrela de Hollywood?",
    "Ele(a) já foi convidado(a) para o Met Gala?",
    "Essa celebridade já ganhou um prêmio de melhor ator/atriz?",
    "Ele(a) já foi o rosto de campanhas de moda famosas?",
    "Essa celebridade já ganhou uma estrela na Calçada da Fama?",
    "Ele(a) já lançou um documentário sobre sua vida?",
    "Essa celebridade é reconhecida como um ícone cultural?",
    "Ele(a) já se envolveu em polêmicas políticas?",
    "Essa celebridade já participou de algum filme de super-heróis?",
    "Ele(a) já foi considerado(a) uma lenda em sua área?",
    "Essa celebridade tem mais de um milhão de seguidores no Instagram?",
    "Ele(a) já lançou uma linha de produtos ou roupas?",
    "Essa celebridade já foi capa da revista Forbes?",
    "Ele(a) é reconhecido(a) por sua voz única?",
    "Essa pessoa já participou de séries ou filmes infantis?",
    "Essa celebridade é famosa por suas postagens nas redes sociais?",
    "Ele(a) já recebeu prêmios de reconhecimento por seu trabalho social?",
    "Essa celebridade já ganhou algum prêmio de música?",
    "Ele(a) já foi casado(a) mais de uma vez?",
    "Essa celebridade é conhecida por seu envolvimento em causas sociais?",
    "Essa pessoa já fez uma aparição no programa de um grande talk show?",
    "Ele(a) já lançou um álbum de grande sucesso?",
    "Essa celebridade é conhecida por suas habilidades de atuação dramática?",
    "Essa pessoa é famosa por seu talento no esporte?",
    "Essa celebridade já foi a pessoa mais comentada nas redes sociais?",
    "Ele(a) já foi entrevistado(a) em programas de televisão do Brasil?",
    "Essa celebridade já trabalhou em projetos de cinema ou televisão no Brasil?",
    "Ele(a) já recebeu prêmios por mais de um talento artístico?",
    "Essa pessoa é conhecida mundialmente?",
    "Essa celebridade já teve seu próprio reality show?",
    "Ele(a) já participou de uma novela de grande sucesso?",
    "Essa pessoa é conhecida por ser polêmica?",
    "Essa celebridade já foi mencionada em músicas?",
    "Ele(a) já fez parte de uma série de filmes?",
    "Essa celebridade já foi embaixadora de uma marca famosa?",
    "Essa pessoa já participou de videoclipes?",
    "Essa celebridade já fez parte de um grande festival?",
    "Essa pessoa é conhecida por sua contribuição ao cinema brasileiro?",
    "Essa celebridade já estrelou em comerciais de TV?",
    "Ele(a) já recebeu prêmios por suas atuações em filmes de comédia?",
    "Essa pessoa já foi indicada ao prêmio de Melhor Atriz/Atriz Coadjuvante?",
    "Ele(a) é uma das pessoas mais influentes no Brasil?",
    "Essa celebridade já gravou duetos com outros artistas famosos?",
    "Essa pessoa já apareceu em listas das mais influentes do mundo?",
    "Essa celebridade já fez par romântico com outra estrela famosa?",
    "Ele(a) já lançou sua própria marca de perfumes?",
    "Essa celebridade já foi vítima de fake news?",
    "Essa pessoa já se envolveu em ações de caridade?",
    "Essa celebridade já foi reconhecida por seu trabalho no Brasil e no exterior?",
    "Ele(a) já foi notícia por escândalos pessoais?",
    "Essa celebridade tem um grande patrimônio financeiro?",
    "Essa pessoa é um(a) cantor(a) de sucesso?",
    "Essa celebridade já foi destaque em filmes de grande bilheteria?",
    "Ele(a) já recebeu indicações para prêmios internacionais?",
    "Essa pessoa é conhecida por sua popularidade na internet?",
    "Essa celebridade já esteve envolvida em projetos de cinema e música?",
    "Ele(a) já foi convidado(a) para apresentar algum grande evento?",
    "Essa celebridade é mais famosa no Brasil ou no exterior?",
    "Essa pessoa já fez parte de campanhas publicitárias de grandes marcas?",
    "Essa celebridade já foi mencionada como um ícone da moda?",
    "Ele(a) é famoso(a) por sua atuação em filmes de super-heróis?",
    "Essa pessoa é uma inspiração para novas gerações?",
    "Essa celebridade já foi eleita a pessoa mais bonita do mundo?",
    "Ele(a) já ganhou o prêmio de Melhor Cantor/Cantora?",
    "Essa celebridade já lançou livros de sua biografia?",
    "Ele(a) é conhecido(a) por sua habilidade como dançarino(a)?",
    "Essa pessoa já participou de uma produção de cinema no Brasil?",
    "Essa celebridade já foi casada(o) com outra pessoa famosa?",
    "Essa celebridade já teve problemas com a justiça?",
    "Ele(a) é reconhecido(a) por seu senso de humor?",
    "Essa pessoa é famosa por ser discreta?",
    "Essa celebridade já gravou parcerias internacionais de música?",
    "Ele(a) já estrelou em um filme baseado em fatos reais?",
    "Essa celebridade tem grande influência nas redes sociais?"
]
