comidas = [
    "Pizza", "Hambúrguer", "Sushi", "Taco", "Lasanha", "Sopa de letras", "Espaguete", "Frango assado",
    "Cachorro-quente", "Torta de maçã", "Salmão grelhado", "Batata frita", "Churrasco", "Ceviche", "Risoto",
    "Pão de alho", "Sorvete de baunilha", "Tapioca", "Coxinha", "Brigadeiro", "Moqueca", "Bacalhau", "Bolo de cenoura", 
    "Acarajé", "Empanada", "Fondue de queijo", "Burrito", "Feijoada","Empadão", "Omelete", "Panqueca", "Salada de alface", "Nachos", "Carne de sol", "Pavê", "Strogonoff",
    "Esfirra", "Croissant", "Donuts", "Macarronada", "Yakissoba", "Paella", "Polenta", "Nhoque",
    "Arroz de polvo", "Pão de queijo", "Crepe", "Ravioli", "Cuscuz marroquino", "Frango à parmegiana", "Bolinho de chuva",
    "Arroz de pato", "Bolinho de bacalhau", "Filé à milanesa", "Caldo verde", "Costela assada", 
    "Pizza de calabresa", "Camarão", "Bobó de camarão", "Quindim", "Escondidinho", "Pudim de leite",
    "Picanha", "Pão de banana", "Frango frito", "Lasanha de berinjela", "Mousse de chocolate", "Vatapá", "Polvo à lagareiro",
    "Sardinha frita", "Costelinha barbecue", "Bacalhau", "Pastel de Belém", "Brigadeiro" , "Beijinho"
    "Bolo de chocolate", "Risoto de camarão", "Galeto", "Sanduíche de pernil", "Torta de frango", "Bruschetta",
    "Salmão grelhado", "Filé mignon", "Purê de batata", "Salada de quinoa", "Sopa de lentilha", "Bife à cavalo",
    "Lula à dorê", "Bolo de fubá", "Feijão tropeiro", "Calzone", "Kebab", "Arroz", "Almondegas", "Panetone",
    "Escondidinho de carne seca", "Pernil assado", "Beirute", "Macaron", "Brownie", "Torta holandesa" , "Mouse de limão" , "Coxinha"
]

perguntasComidas = [
    "Essa comida é mais salgada ou doce?",
    "Você comeria isso no café da manhã?",
    "É um prato típico de algum país?",
    "Essa comida pode ter carne?",
    "Você come isso com as mãos?",
    "Você já fez essa comida?",
    "Você acha que crianças gostariam disso?",
    "Essa comida é melhor quente ou fria?",
    "Precisa de muito tempo para preparar essa comida?",
    "Você consegue empilhar quantas dessa comida",
    "Você comeria isso em um restaurante elegante?",
    "Essa comida é comum em festas?",
    "Você encontraria em um fast food?",
    "Essa comida é melhor com algum molho?",
    "Onde Você come esse alimento?",
    "Esse prato ficaria bom se fosse mais picante?",
    "Você acha que essa comida tem um cheiro forte?",
    "Se tivesse uma lei proibindo essa comida qual seria o motivo?",
    "Essa comida é feita normalmente para servir quantas pessoas?",
    "Ela é feita no forno?",
    "Essa comida pode ser considerada um lanche?",
    "É servido em porções grandes ou pequenas?",
    "Você acha que essa comida é cara?",
    "Essa comida é típica de alguma região do Brasil?",
    "Pode ser comido de pé ou precisa de mesa?",
    "É um prato que tem muitos ingredientes?",
    "Essa comida tem algum ingrediente cru?",
    "Pode ser feito em uma churrasqueira?",
    "Essa comida precisa ser cortada antes de comer?",
    "É comum encontrar essa comida em food trucks?",
    "Essa comida faz parte de alguma dieta especial?",
    "Esse prato é servido em restaurantes de fast food?",
    "Você consegue fazer esse prato em casa facilmente?",
    "Você comeria isso em uma viagem?",
    "É uma comida comum no almoço?",
    "Essa comida é vegetariana?",
    "Ela é feita com farinha?",
    "É uma comida assada?",
    "Essa comida é típica de qual estação do ano?",
    "Você comeria isso em um dia quente?",
    "Essa comida tem algum ingrediente exótico?",
    "É um prato comum para o jantar?",
    "Pode ser servido como acompanhamento?",
    "Essa comida é crocante?",
    "Tem algum ingrediente com sabor cítrico?",
    "Esse prato é famoso mundialmente?",
    "Você colocaria ketchup nessa comida?",
    "Ela é feita com algum tipo de massa?",
    "Você acha que essa comida engorda?",
    "Essa comida faz parte de algum tipo de dieta?",
    "É uma comida que combina com bebidas alcoólicas?",
    "Você precisaria de talheres para comer isso?",
    "Essa comida é muito popular no Brasil?",
    "Esse prato é doce ou salgado?",
    "É uma comida fácil de encontrar em restaurantes?",
    "Você comeria isso em um piquenique?",
    "Essa comida é comum em festas de aniversário?",
    "Pode ser servido em uma taça?",
    "É uma comida gourmet?",
    "Essa comida é tradicional de algum lugar específico?",
    "É uma comida que você comeria em um encontro romântico?",
    "Você comeria isso durante um filme?",
    "Essa comida leva açúcar?",
    "Pode ser encontrada em supermercados?",
    "É uma comida que você levaria para uma viagem?",
    "Esse prato tem muitos condimentos?",
    "Você comeria isso como um petisco?",
    "Essa comida é muito popular nas redes sociais?",
    "Essa comida tem algum nome difícil de pronunciar?",
    "Ela é feita com algum tipo de carne vermelha?",
    "Essa comida é normalmente servida em porções individuais?",
    "É uma comida que leva bastante tempero?",
    "Ela pode ser recheada?",
    "Essa comida tem algum ingrediente que seja verde?",
    "Essa comida leva queijo?",
    "Pode ser acompanhada de arroz?",
    "Essa comida é frita?",
    "Você colocaria pimenta nessa comida?",
    "Essa comida é comum em lanchonetes?",
    "Ela é feita com algum tipo de grão?",
    "Essa comida é picante?",
    "Você comeria essa comida no café da manhã?",
    "Ela é vendida em barracas de rua?",
    "Essa comida pode ser feita com sobras de outros pratos?",
    "Essa comida é típica de algum país europeu?",
    "Essa comida é feita com ingredientes frescos?",
    "É uma comida que você comeria com pão?",
    "Pode ser servida em uma travessa?",
    "Essa comida tem algum tipo de fruta?",
    "É uma comida que combina com sobremesas?",
    "Você encontraria essa comida em um rodízio?",
    "Essa comida é tradicional em algum feriado?",
    "Você comeria isso em um dia de calor?",
    "Essa comida tem algum tipo de bebida como ingrediente?",
    "É uma comida que leva muita gordura?",
    "Essa comida tem um preparo demorado?",
    "Pode ser servido com algum tipo de bebida alcoólica?",
    "Essa comida é uma especialidade de algum restaurante?",
    "Essa comida tem algum nome engraçado?",
    "Pode ser um prato principal?",
    "Você comeria isso em um restaurante especializado?",
    "Essa comida leva batata como ingrediente?",
    "É uma comida que faz parte de uma dieta específica?",
    "Você precisaria de uma receita para preparar essa comida?",
    "Essa comida é acompanhada de salada?",
    "Você comeria isso em um churrasco?",
    "Essa comida tem um sabor ácido?",
    "É uma comida que você pediria por delivery?",
    "Essa comida é vendida em feiras?",
    "Você comeria isso como sobremesa?",
    "Essa comida é leve ou pesada?",
    "Essa comida é feita com algum tipo de massa?",
    "Ela pode ser servida com feijão?",
    "Essa comida pode ser encontrada em mercados?",
    "Você comeria isso em um dia chuvoso?",
    "Essa comida é encontrada em buffets?",
    "Você adicionaria molho nessa comida?",
    "Ela é servida com algum tipo de pão?",
    "Essa comida leva carne de porco?",
    "Pode ser comida fria?",
    "Essa comida leva leite ou derivados?",
    "Você comeria isso em uma viagem internacional?",
    "Ela é feita com algum tipo de marisco?",
    "Essa comida é popular em festas temáticas?",
    "Ela tem um nome que lembra um país?",
    "Essa comida é normalmente grelhada?",
    "Pode ser feita na panela de pressão?",
    "Ela tem algum tipo de cobertura?",
    "Essa comida é vendida em porções pequenas?",
    "Você encontraria essa comida em um quiosque na praia?",
    "Pode ser comida de café da tarde?",
    "Essa comida tem algum sabor defumado?",
    "Você encontraria essa comida em uma padaria?",
    "Essa comida leva algum tipo de massa?",
    "Pode ser preparada com manteiga?",
    "Essa comida é acompanhada de molho?",
    "Essa comida pode ser servida em festas infantis?",
    "Você comeria isso como lanche da tarde?",
    "Ela pode ser servida com vegetais?",
    "Essa comida é tipicamente grelhada?",
    "Pode ser uma opção para vegetarianos?",
    "Você acha que essa comida é muito popular?",
    "Essa comida tem algum tipo de cobertura crocante?",
    "Ela pode ser feita com ingredientes caseiros?",
    "Você comeria essa comida em uma viagem ao exterior?",
    "Essa comida tem origem em algum país específico?",
    "Você encontraria essa comida em um restaurante temático?",
    "Essa comida tem um sabor adocicado?",
    "Pode ser comida em porções pequenas?",
    "Essa comida pode ser servida em uma tábua?",
    "É uma comida comum em lanchonetes?",
    "Você comeria isso com uma bebida quente?",
    "Essa comida tem algum ingrediente que vem do mar?",
    "Essa comida leva mais de cinco ingredientes?",
    "Ela pode ser comida diretamente com as mãos?",
    "Essa comida é encontrada em praças de alimentação?",
    "Pode ser uma comida típica de festas juninas?",
    "Essa comida é feita com algum tipo de grão?",
    "Você comeria isso em uma data especial?",
    "Ela pode ser servida em um prato fundo?",
    "Essa comida é acompanhada de alguma bebida alcoólica?",
    "Você encontraria essa comida em uma feira de rua?",
    "Essa comida é servida em porções individuais?",
    "Ela é muito popular em festas de casamento?",
    "Pode ser preparada de maneira simples?",
    "Essa comida tem um sabor amargo?",
    "Essa comida tem algum tipo de grão?",
    "Ela é feita com leite?",
    "Essa comida tem um preparo rápido?",
    "Pode ser encontrada em restaurantes fast food?",
    "Essa comida tem origem italiana?",
    "Pode ser comida com arroz?",
    "Essa comida tem algum tipo de acompanhamento?",
    "Ela é servida com alguma bebida específica?",
    "Você comeria isso em um evento esportivo?",
    "Essa comida tem algum ingrediente comum no café da manhã?",
    "Ela pode ser servida em um prato grande?",
    "Você comeria isso com uma bebida gelada?",
    "Essa comida é feita com queijo?",
    "Ela é uma comida popular no exterior?",
    "Pode ser servida como prato principal?",
    "Você encontraria essa comida em uma festa temática?",
    "Ela é acompanhada de salada?",
    "Essa comida pode ser comida quente ou fria?",
    "Ela tem algum tipo de molho apimentado?",
    "Essa comida é um prato típico de qual país?",
    "Ela pode ser servida com pão?",
    "Essa comida é feita com frutos do mar?",
    "Você comeria essa comida em um dia de chuva?",
    "Ela é feita com ingredientes frescos?",
    "Pode ser encontrada em bares?",
    "Essa comida é considerada requintada?",
    "Você comeria isso em um churrasco?",
    "Essa comida é uma sobremesa?",
    "Pode ser uma comida típica de café da manhã?",
    "Ela é servida com molho doce?",
    "Essa comida é muito popular em restaurantes de fast food?",
    "Ela tem algum tipo de carne?",
    "Essa comida é comumente servida com batatas?",
    "Você comeria isso em um piquenique?",
    "Essa comida tem um sabor forte?",
    "Ela é feita com farinha?",
    "Essa comida é comum em festivais?",
    "Ela pode ser acompanhada de arroz?",
    "Você comeria isso em um dia frio?",
    "Essa comida é feita com ingredientes exóticos?",
    "Ela é servida com algum tipo de salada?",
    "Essa comida pode ser encontrada em festas de casamento?",
    "Ela é feita com carne bovina?",
    "Você comeria isso em uma festa infantil?",
    "Essa comida pode ser encontrada em mercados de rua?",
    "Ela é preparada com temperos fortes?",
    "Essa comida é servida em pequenas porções?",
    "Ela pode ser encontrada em restaurantes de fast food?",
    "Essa comida é feita com ingredientes típicos brasileiros?",
    "Você comeria isso em uma viagem ao exterior?",
    "Ela é feita com carne de frango?",
    "Essa comida tem origem em qual país?",
    "Você comeria isso em um dia ensolarado?",
    "Essa comida tem um sabor salgado?",
    "Ela pode ser acompanhada de vinho?",
    "Essa comida é feita com ingredientes locais?",
    "Ela é uma comida típica de qual região?",
    "Você comeria isso como lanche da tarde?",
    "Essa comida é feita com ingredientes naturais?",
    "Ela pode ser encontrada em food trucks?",
    "Essa comida é servida em grandes porções?",
    "Você comeria isso em uma refeição ao ar livre?",
    "Ela é uma comida leve?",
    "Essa comida é muito popular entre jovens?",
    "Você comeria isso em uma viagem de férias?",
    "Ela é uma comida que combina com sobremesas?",
    "Essa comida é comumente vendida em quiosques de praia?",
    "Ela pode ser preparada em menos de 30 minutos?",
    "Você comeria isso em um evento especial?",
    "Essa comida tem algum tipo de ingrediente incomum?",
    "Ela pode ser preparada com ingredientes simples?",
    "Essa comida é tipicamente grelhada?",
    "Você comeria isso em um restaurante tradicional?",
    "Essa comida é famosa por seu sabor único?",
    "Ela pode ser acompanhada de alguma bebida específica?",
    "Essa comida é feita com ingredientes da estação?",
    "Você comeria isso em uma refeição leve?",
    "Ela pode ser comida diretamente com as mãos?",
    "Essa comida é conhecida mundialmente?",
    "Você comeria isso como um lanche rápido?",
    "Essa comida pode ser acompanhada de molho picante?",
    "Ela é uma comida popular em festas familiares?",
    "Essa comida tem um preparo complicado?",
    "Você comeria isso em um evento esportivo?",
    "Essa comida é feita com ingredientes frescos?",
    "Ela pode ser encontrada em padarias tradicionais?",
    "Essa comida é servida com algum tipo de molho?",
    "Ela pode ser comida como aperitivo?",
    "Essa comida é muito popular em redes sociais?",
    "Você comeria isso como um prato principal?",
    "Ela pode ser preparada rapidamente?",
    "Essa comida é comum em eventos culturais?",
    "Você comeria isso em um café da manhã especial?",
    "Essa comida é feita com ingredientes saudáveis?",
    "Ela pode ser servida com algum tipo de bebida alcoólica?",
    "Essa comida é muito consumida em festas?",
    "Ela pode ser encontrada em restaurantes finos?",
    "Você comeria isso em uma data comemorativa?"
]
