# Generated by Django 5.1.2 on 2024-10-27 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_enquete_opcao_voto'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuarios',
            new_name='Usuario',
        ),
    ]
