# Generated by Django 5.1.2 on 2024-11-05 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_voto_usuario_delete_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='opcao',
            name='votos',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Voto',
        ),
    ]
