# Generated by Django 5.1.3 on 2024-12-02 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Musica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lancamento', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('titulo', models.CharField(max_length=100)),
                ('artista', models.CharField(max_length=100)),
                ('url', models.URLField(unique=True)),
                ('capa', models.ImageField(upload_to='capas/')),
            ],
            options={
                'verbose_name': 'Musica',
                'verbose_name_plural': 'album',
            },
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lancamento', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('user', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('comentario', models.TextField(blank=True, default='')),
                ('voto', models.BooleanField(choices=[(True, 'Like'), (False, 'Dislike')], default=True)),
                ('musica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='musica.musica')),
            ],
            options={
                'verbose_name': 'Avaliação',
                'verbose_name_plural': 'Avaliações',
                'unique_together': {('email', 'musica')},
            },
        ),
    ]
