Videogames = [
    "Super Mario",
    "Pac-Man",
    "Minecraft",
    "The Legend of Zelda",
    "Call of Duty",
    "Fortnite",
    "Grand Theft Auto V",
    "FIFA",
    "League of Legends",
    "Counter-Strike",
    "The Sims",
    "Among Us",
    "Overwatch",
    "Tetris",
    "Sonic the Hedgehog",
    "Street Fighter",
    "Pokémon",
    "Red Dead Redemption",
    "Fall Guys",
    "Candy Crush",
    "Roblox",
    "Dota 2",
    "Final Fantasy",
    "Resident Evil",
    "Dark Souls",
    "Halo",
    "The Elder Scrolls",
    "Apex Legends",
    "Battlefield",
    "Cyberpunk 2077",
    "Assassin's Creed",
    "DOOM",
    "God of War",
    "The Witcher 3",
    "Valorant",
    "Rocket League",
    "Diablo",
    "Mortal Kombat",
    "Donkey Kong",
    "Metal Gear Solid",
    "PUBG",
    "Far Cry",
    "Cuphead",
    "Portal",
    "Shadow of the Colossus",
    "Bioshock",
    "Zelda",
    "Pokémon",
    "The Last of Us",
    "Crash Bandicoot",
    "Left 4 Dead",
    "Forza Horizon",
    "Genshin Impact",
    "Uncharted",
    "Ghost of Tsushima",
    "Spider-Man (PS4)",
    "Forza horizon",
    "Elden Ring",
    "Terraria",
    "Cuphead",
    "League of Legends: Wild Rift",
    "F1 2021",
    "Horizon Zero Dawn",
    "Just Dance",
    "Fortnite Save the World",
    "Plants vs. Zombies",
    "Stardew Valley",
    "Bomba Patch"
]

perguntasVideogames = [
    "Esse jogo é um clássico dos anos 80?",
    "Esse jogo é jogado em primeira pessoa?",
    "Essa franquia de jogos é conhecida por suas histórias profundas?",
    "Esse jogo é exclusivo de uma plataforma?",
    "Esse jogo tem gráficos realistas?",
    "Esse jogo foi lançado nos últimos cinco anos?",
    "Esse jogo tem uma versão online multiplayer?",
    "Esse jogo é considerado um jogo de terror?",
    "Esse jogo tem elementos de construção?",
    "Esse jogo foi criado por uma empresa japonesa?",
    "Esse jogo é popular em campeonatos de eSports?",
    "Esse jogo é jogado por milhões de pessoas ao redor do mundo?",
    "Esse personagem de jogo usa uma arma famosa?",
    "Esse jogo é famoso por seu mundo aberto?",
    "Esse jogo tem um protagonista icônico?",
    "Esse jogo tem suporte para realidade virtual?",
    "Esse jogo tem uma sequência lançada?",
    "Esse jogo é cooperativo?",
    "Esse jogo envolve missões de exploração?",
    "Esse jogo tem uma trilha sonora famosa?",
    "Esse jogo foi adaptado para um filme?",
    "Esse jogo é um jogo de luta?",
    "Esse jogo tem algum tipo de magia?",
    "Esse jogo foi lançado por uma empresa indie?",
    "Esse jogo tem gráficos pixelados?",
    "Esse jogo permite criar seu próprio personagem?",
    "Esse jogo tem diversos finais diferentes?",
    "Esse jogo tem um sistema de progressão por níveis?",
    "Esse jogo tem combate corpo a corpo?",
    "Esse jogo é ambientado no espaço?",
    "Esse jogo é conhecido por sua dificuldade elevada?",
    "Esse jogo é baseado em uma série de TV ou filme?",
    "Esse jogo tem modo competitivo?",
    "Esse jogo se passa em um futuro distópico?",
    "Esse jogo tem zumbis ou criaturas mutantes?",
    "Esse jogo é jogado em turnos?",
    "Esse jogo tem uma comunidade ativa de modders?",
    "Esse jogo foi aclamado pela crítica?",
    "Esse jogo permite pilotar veículos?",
    "Esse jogo tem elementos de puzzle ou quebra-cabeças?",
    "Esse jogo tem uma história emocional?",
    "Esse jogo se passa em um ambiente de fantasia medieval?",
    "Esse jogo permite controlar um exército?",
    "Esse jogo tem gráficos em estilo cartoon?",
    "Esse jogo foi lançado para dispositivos móveis?",
    "Esse jogo tem modos de jogo com temporadas ou eventos?",
    "Esse jogo envolve estratégia em tempo real?",
    "Esse jogo foi remasterizado ou refeito?",
    "Esse jogo tem microtransações?",
    "Esse jogo foi criticado por seu enredo?",
    "Esse jogo se passa em uma ilha?",
    "Esse jogo é inspirado por mitologia ou história real?",
    "Esse jogo permite personalizar suas armas?",
    "Esse jogo tem uma grande base de fãs no Brasil?",
    "Esse jogo possui chefes difíceis de derrotar?",
    "Esse jogo tem um mapa de mundo aberto massivo?",
    "Esse jogo envolve resolver crimes ou mistérios?",
    "Esse jogo tem uma história pós-apocalíptica?",
    "Esse jogo é jogado em equipe?",
    "Esse jogo possui elementos de RPG?",
    "Esse jogo tem um sistema de criação de itens?",
    "Esse jogo permite interação com NPCs?",
    "Esse jogo foi influenciado por outro jogo famoso?",
    "Esse jogo é conhecido por suas cenas cinematográficas?",
    "Esse jogo é classificado para maiores de 18 anos?",
    "Esse jogo possui personagens femininas jogáveis?",
    "Esse jogo permite viajar para diferentes planetas ou dimensões?",
    "Esse jogo foi feito por uma empresa americana?",
    "Esse jogo já recebeu uma grande atualização ou expansão?",
    "Esse jogo tem missões secundárias complexas?",
    "Esse jogo envolve espionagem ou furtividade?",
    "Esse jogo foi indicado ou ganhou prêmios?",
    "Esse jogo tem gráficos 3D?",
    "Esse jogo é baseado em quadrinhos ou mangás?",
    "Esse jogo tem um protagonista que não fala?",
    "Esse jogo tem um multiplayer competitivo?",
    "Esse jogo tem uma campanha single-player?",
    "Esse jogo permite voar ou levitar?",
    "Esse jogo envolve invadir bases ou castelos?",
    "Esse jogo tem elementos de horror psicológico?",
    "Esse jogo permite controlar robôs ou mechas?",
    "Esse jogo é ambientado em uma cidade futurista?",
    "Esse jogo permite fazer escolhas morais?",
    "Esse jogo tem um protagonista carismático?",
    "Esse jogo é conhecido por seu humor?",
    "Esse jogo foi feito por um estúdio independente?",
    "Esse jogo tem missões temporizadas?",
    "Esse jogo é baseado em um livro famoso?",
    "Esse jogo envolve viagens no tempo?",
    "Esse jogo tem combates aéreos ou espaciais?",
    "Esse jogo tem múltiplos modos de jogo?",
    "Esse jogo é considerado inovador para seu gênero?",
    "Esse jogo é jogado principalmente por crianças?",
    "Esse jogo permite construir e gerenciar cidades ou civilizações?",
    "Esse jogo é inspirado por eventos históricos reais?",
    "Esse jogo tem personagens com superpoderes?",
    "Esse jogo é considerado um clássico cult?",
    "Esse jogo tem uma jogabilidade não-linear?",
    "Esse jogo tem atualizações frequentes?",
    "Esse jogo se passa em um futuro distante?",
    "Esse jogo permite criar seu próprio mundo ou mapa?",
    "Esse jogo tem um protagonista humano?",
    "Esse jogo tem missões em ambiente subaquático?",
    "Esse jogo envolve pilotar naves espaciais?",
    "Esse jogo tem um modo 'sobrevivência'?",
    "Esse jogo tem um enredo surpreendente?",
    "Esse jogo tem monstros ou criaturas mitológicas?",
    "Esse jogo tem um vilão icônico?",
    "Esse jogo foi um grande sucesso comercial?",
    "Esse jogo tem gráficos em estilo anime?",
    "Esse jogo é jogado com controle de movimento?",
    "Esse jogo permite viajar entre diferentes reinos?",
    "Esse jogo tem suporte para crossplay?",
    "Esse jogo tem uma grande comunidade de fãs nas redes sociais?",
    "Esse jogo tem opções de dificuldade customizáveis?",
    "Esse jogo tem cenários baseados em cidades reais?",
    "Esse jogo permite montar animais ou criaturas?",
    "Esse jogo tem mecânicas de furtividade?",
    "Esse jogo foi criticado por seus gráficos?",
    "Esse jogo tem uma versão remasterizada ou remake?",
    "Esse jogo envolve resolver quebra-cabeças para avançar?",
    "Esse jogo permite usar magia ou feitiços?",
    "Esse jogo tem uma trilha sonora premiada?",
    "Esse jogo se passa em uma distopia futurista?",
    "Esse jogo tem opções de diálogo que afetam a história?",
    "Esse jogo tem personagens não humanos?",
    "Esse jogo tem uma mecânica de combate em tempo real?",
    "Esse jogo permite controlar mais de um personagem?",
    "Esse jogo tem sequências ou expansões planejadas?",
    "Esse jogo tem eventos sazonais ou de feriados?",
    "Esse jogo permite explorar florestas ou ambientes naturais?",
    "Esse jogo tem missões furtivas?",
    "Esse jogo tem gráficos estilo retro?",
    "Esse jogo permite personalizar suas habilidades?",
    "Esse jogo é jogado com mouse e teclado?",
    "Esse jogo tem um enredo inspirado em mitologias?",
    "Esse jogo foi lançado no PlayStation?",
    "Esse jogo é considerado um marco na história dos videogames?",
    "Esse jogo tem uma comunidade ativa de criadores de conteúdo?",
    "Esse jogo tem modos cooperativos?",
    "Esse jogo envolve piratas ou navegação?",
    "Esse jogo tem algum tipo de criatura alienígena?",
    "Esse jogo foi criticado por ser repetitivo?",
    "Esse jogo tem batalhas épicas contra chefes?",
    "Esse jogo tem personagens que podem evoluir?",
    "Esse jogo tem uma sequência famosa?",
    "Esse jogo foi lançado no Xbox?",
    "Esse jogo tem um protagonista em busca de vingança?",
    "Esse jogo é jogado em terceira pessoa?",
    "Esse jogo permite criar guildas ou grupos?",
    "Esse jogo tem classes de personagens diferentes?",
    "Esse jogo permite interagir com objetos no cenário?",
    "Esse jogo tem mecânicas de hack and slash?",
    "Esse jogo tem puzzles complexos?",
    "Esse jogo tem suporte para controle de movimento?",
    "Esse jogo foi lançado no Nintendo Switch?",
    "Esse jogo tem um estilo de arte único?",
    "Esse jogo é baseado em uma franquia de sucesso?",
    "Esse jogo envolve corridas ou competições?",
    "Esse jogo foi feito por um pequeno estúdio?",
    "Esse jogo tem uma grande quantidade de itens colecionáveis?",
    "Esse jogo tem um sistema de economia dentro do jogo?",
    "Esse jogo é focado em exploração espacial?",
    "Esse jogo tem modo de criação ou construção?",
    "Esse jogo tem desafios diários ou semanais?",
    "Esse jogo é jogado com personagens personalizáveis?",
    "Esse jogo permite fazer parkour ou movimentos acrobáticos?",
    "Esse jogo tem gráficos ultra-realistas?",
    "Esse jogo tem alguma relação com esportes?",
    "Esse jogo permite criar alianças ou facções?",
    "Esse jogo foi inspirado por outra obra de ficção?",
    "Esse jogo permite viajar no tempo?",
    "Esse jogo tem um protagonista silencioso?",
    "Esse jogo permite capturar ou domesticar criaturas?",
    "Esse jogo envolve pilhagem e saques?",
    "Esse jogo tem algum tipo de criatura mitológica?",
    "Esse jogo foi desenvolvido na Europa?",
    "Esse jogo tem batalhas espaciais?",
    "Esse jogo envolve resolver enigmas para progredir?",
    "Esse jogo tem um protagonista infantil ou adolescente?",
    "Esse jogo foi desenvolvido por um estúdio japonês?",
    "Esse jogo é inspirado por culturas antigas?",
    "Esse jogo tem elementos de ficção científica?",
    "Esse jogo foi lançado nos últimos dois anos?",
    "Esse jogo tem uma trilha sonora orquestrada?",
    "Esse jogo tem missões no submundo ou em reinos infernais?",
    "Esse jogo envolve proteger uma cidade ou civilização?",
    "Esse jogo tem suporte para múltiplos idiomas?",
    "Esse jogo permite construir ou modificar veículos?",
    "Esse jogo foi lançado pela primeira vez nos anos 2000?",
    "Esse jogo tem personagens que podem usar feitiços?",
    "Esse jogo tem opções de multiplayer online?",
    "Esse jogo tem uma história emocionante?",
    "Esse jogo tem personagens com superpoderes?",
    "Esse jogo envolve explorar o fundo do mar?",
    "Esse jogo tem um mapa que muda com o tempo?",
    "Esse jogo tem batalhas massivas com muitos jogadores?",
    "Esse jogo permite modificar o terreno ao seu redor?",
    "Esse jogo tem personagens baseados em figuras históricas?",
    "Esse jogo tem uma narrativa ramificada com múltiplas escolhas?"
]